FROM python:3.7.4

WORKDIR /app

COPY ./requirements.txt  ./requirements.txt

RUN pip install -r requirements.txt

COPY ./entrypoint.sh ./entrypoint.sh
COPY ./app .


# Set the entrypoint.sh file to be executable
RUN chmod +x ./entrypoint.sh

# Execute the entrypoint.sh
ENTRYPOINT [ "./entrypoint.sh" ]
